### ISSUE TITLE
Improvement Browsers Meta Box

### ISSUE THREAD

**Issue by mehrshaddarzi** [wp-statistics/wp-statistics#278]
- [x] Remove PHP Color and Use Js Color
- [x] add a custom browser to show
- [x] Add Time Range to Meta Box
- [x] set Datapicker similar Hits
